name: microovn
icon: microovn.png
base: core22
assumes:
 - snapd2.59
version: git
grade: stable
source-code: https://github.com/canonical/microovn.git
summary: Simple clustered OVN deployment
description: |-
 Self-contained self-deployment with clustering.

confinement: strict

apps:
  # Service
  daemon:
    command: commands/daemon.start
    daemon: simple
    plugs:
      - network
      - network-bind
    slots:
      - microovn

  central:
    command: commands/central.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind

  chassis:
    command: commands/chassis.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
      - network-control
      - process-control
      - system-trace
      - hardware-observe

  switch:
    command: commands/switch.start
    daemon: simple
    install-mode: disable
    refresh-mode: endure
    plugs:
      - firewall-control
      - hardware-observe
      - hugepages-control
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace

  # Commands
  microovn:
    command: commands/microovn
    plugs:
      - network

  ovn-appctl:
    command: commands/ovn-appctl
    plugs:
      - network
  ovn-nbctl:
    command: commands/ovn-nbctl
    plugs:
      - network
  ovn-sbctl:
    command: commands/ovn-sbctl
    plugs:
      - network

  ovs-appctl:
    command: commands/ovs-appctl
    plugs:
      - network
  ovs-dpctl:
    command: commands/ovs-dpctl
    plugs:
      - network
  ovs-ofctl:
    command: commands/ovs-ofctl
    plugs:
      - network
  ovs-vsctl:
    command: commands/ovs-vsctl
    plugs:
      - network

parts:
  # Dependencies
  dqlite:
    after:
      - raft
    source: https://github.com/canonical/dqlite
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - libsqlite3-0
    build-packages:
      - libuv1-dev
      - libsqlite3-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libdqlite*so*
      - lib/*/libuv*

  raft:
    source: https://github.com/canonical/raft
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - liblz4-1
    build-packages:
      - libuv1-dev
      - liblz4-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libraft*so*
      - lib/*/libuv.so*

  ovn:
    plugin: autotools
    source: https://github.com/ovn-org/ovn.git
    source-type: git
    override-build: |
      # This OVS build is used as a build time dependency for OVN and not the
      # version installed.  See the `ovs` part for the installed artifact.
      cd ovs
      ./boot.sh
      ./configure \
        --prefix=/ \
        --localstatedir=/var \
        --enable-ssl \
        --sysconfdir=/etc
      make -j$CRAFT_PARALLEL_BUILD_COUNT
      cd ..
      ./boot.sh
      ./configure \
        --prefix=/ \
        --localstatedir=/var \
        --enable-ssl \
        --sysconfdir=/etc
      make -j$CRAFT_PARALLEL_BUILD_COUNT
      make check TESTSUITEFLAGS="-j $CRAFT_PARALLEL_BUILD_COUNT"
      make install DESTDIR=$CRAFT_PART_INSTALL

      mkdir -p "${CRAFT_PART_INSTALL}/etc/ovn/"
    build-packages:
      - autoconf
      - automake
      - bzip2
      - graphviz
      - libcap-ng-dev
      - libnuma-dev
      - libpcap-dev
      - libssl-dev
      - libtool
      - libudev-dev
      - libunbound-dev
      - openssl
      - pkg-config
      - procps
      - python3-all-dev
      - python3-setuptools
      - python3-sortedcontainers
      - python3-sphinx
      - tcpdump
    prime:
     - bin/ovn-appctl
     - bin/ovn-controller
     - bin/ovn-nbctl
     - bin/ovn-northd
     - bin/ovn-sbctl
     - etc/ovn
     - share/ovn

  ovs:
    plugin: autotools
    source: https://github.com/openvswitch/ovs.git
    source-type: git
    build-environment:
      - CONFIGURE_PARAMETERS: --prefix=/ --localstatedir=/var --enable-ssl --sysconfdir=/etc
    override-build: |
      ./boot.sh
      ./configure $CONFIGURE_PARAMETERS
      make -j$CRAFT_PARALLEL_BUILD_COUNT
      make install DESTDIR=$CRAFT_PART_INSTALL
      make check TESTSUITEFLAGS="-j$CRAFT_PARALLEL_BUILD_COUNT"
    build-packages:
      - autoconf
      - automake
      - bzip2
      - dh-python
      - graphviz
      - iproute2
      - libcap-ng-dev
      - libdbus-1-dev
      - libnuma-dev
      - libpcap-dev
      - libssl-dev
      - libtool
      - libunbound-dev
      - openssl
      - pkg-config
      - procps
      - python3-all-dev
      - python3-setuptools
      - python3-sortedcontainers
      - python3-sphinx
    stage-packages:
      - libevent-2.1-7
      - libunbound8
      - python3-sortedcontainers
    organize:
      usr/bin/: bin/
      usr/sbin/: bin/
      sbin/: bin/
      usr/lib/: lib/
      usr/share/: share/
    prime:
     - bin/ovs-appctl
     - bin/ovs-dpctl
     - bin/ovs-ofctl
     - bin/ovs-vsctl
     - bin/ovs-vswitchd
     - bin/ovsdb-client
     - bin/ovsdb-server
     - bin/ovsdb-tool
     - lib/*/libevent-2.1.so*
     - lib/*/libunbound.so*
     - share/openvswitch

  # Main part
  microovn:
    source: microovn/
    after:
      - dqlite
    build-snaps:
      - go
    plugin: nil
    override-pull: |
      craftctl default
      set -ex

      # Download the dependencies
      go get -d -v ./...
    override-build: |
      set -ex

      # Setup build environment
      export CGO_CFLAGS="-I${CRAFT_STAGE}/include/ -I${CRAFT_STAGE}/usr/local/include/"
      export CGO_LDFLAGS="-L${CRAFT_STAGE}/lib/ -L${CRAFT_STAGE}/usr/local/lib/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

      # Build the binaries
      go build -o "${CRAFT_PART_INSTALL}/bin/microovn" ./cmd/microovn
      go build -o "${CRAFT_PART_INSTALL}/bin/microovnd" -tags=libsqlite3 ./cmd/microovnd
    prime:
      - bin/microovn
      - bin/microovnd

  wrappers:
    plugin: dump
    source: snapcraft/
