package ovn

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
	"time"

	"github.com/canonical/lxd/shared/logger"
	"github.com/canonical/microcluster/cluster"
	"github.com/canonical/microcluster/state"

	"github.com/canonical/microovn/microovn/database"
	"github.com/canonical/microovn/microovn/ovn/paths"
)

var ovnEnvTpl = template.Must(template.New("ovnEnvTpl").Parse(`# # Generated by MicroOVN, DO NOT EDIT.
OVN_INITIAL_NB="{{ .nbInitial }}"
OVN_INITIAL_SB="{{ .sbInitial }}"
OVN_NB_CONNECT="{{ .nbConnect }}"
OVN_SB_CONNECT="{{ .sbConnect }}"
OVN_LOCAL_IP="{{ .localAddr }}"
`))

// networkProtocol returns appropriate network protocol that should be used
// by OVN services.
func networkProtocol(s *state.State) string {
	_, _, err := getCA(s)
	if err != nil {
		return "tcp"
	}
	return "ssl"
}

// Builds environment variable strings for OVN.
func environmentString(s *state.State, port int) (string, string, error) {
	var err error
	var servers []database.Service
	var clusterMap map[string]cluster.InternalClusterMember
	err = s.Database.Transaction(s.Context, func(ctx context.Context, tx *sql.Tx) error {
		serviceName := "central"
		servers, err = database.GetServices(ctx, tx, database.ServiceFilter{Service: &serviceName})
		if err != nil {
			return err
		}

		clusterMembers, err := cluster.GetInternalClusterMembers(ctx, tx)
		if err != nil {
			return err
		}

		clusterMap = make(map[string]cluster.InternalClusterMember, len(clusterMembers))
		for _, clusterMember := range clusterMembers {
			clusterMap[clusterMember.Name] = clusterMember
		}

		return nil
	})
	if err != nil {
		return "", "", err
	}

	addresses := make([]string, 0, len(servers))
	var initialString string
	protocol := networkProtocol(s)
	for i, server := range servers {
		member := clusterMap[server.Member]
		memberAddr, err := netip.ParseAddrPort(member.Address)
		if err != nil {
			return "", "", err
		}

		if i == 0 {
			initialString = memberAddr.Addr().String()
			if memberAddr.Addr().Is6() {
				initialString = "[" + initialString + "]"
			}
		}

		addresses = append(
			addresses,
			fmt.Sprintf("%s:%s",
				protocol,
				net.JoinHostPort(memberAddr.Addr().String(), strconv.Itoa(port)),
			),
		)
	}

	return strings.Join(addresses, ","), initialString, nil
}

func generateEnvironment(s *state.State) error {
	// Get the servers.
	nbConnect, nbInitial, err := environmentString(s, 6641)
	if err != nil {
		return err
	}

	sbConnect, sbInitial, err := environmentString(s, 6642)
	if err != nil {
		return err
	}

	// Generate ovn.env.
	fd, err := os.OpenFile(paths.OvnEnvFile(), os.O_CREATE|os.O_TRUNC|os.O_RDWR, 0644)
	if err != nil {
		return fmt.Errorf("Couldn't open ovn.env: %w", err)
	}
	defer fd.Close()

	localAddr := s.Address().Hostname()
	if ip, err := netip.ParseAddr(localAddr); err == nil && ip.Is6() {
		localAddr = "[" + localAddr + "]"
	}

	err = ovnEnvTpl.Execute(fd, map[string]any{
		"localAddr": localAddr,
		"nbInitial": nbInitial,
		"sbInitial": sbInitial,
		"nbConnect": nbConnect,
		"sbConnect": sbConnect,
	})
	if err != nil {
		return fmt.Errorf("Couldn't render ovn.env: %w", err)
	}

	return nil
}

func createPaths() error {
	// Create our various paths.
	for _, path := range paths.RequiredDirs() {
		err := os.MkdirAll(path, 0700)
		if err != nil {
			return fmt.Errorf("Unable to create %q: %w", path, err)
		}
	}

	return nil
}

// cleanupPaths backs up directories defined by paths.BackupDirs and then removes directories
// created by createPaths function. This effectively removes any data created during MicroOVN runtime.
func cleanupPaths() error {
	var errs []error

	// Create timestamped backup dir
	backupDir := fmt.Sprintf("backup_%d", time.Now().Unix())
	backupPath := filepath.Join(paths.Root(), backupDir)
	err := os.Mkdir(backupPath, 0750)
	if err != nil {
		errs = append(
			errs,
			fmt.Errorf(
				"failed to create backup directory '%s'. Refusing to continue with data removal: %s",
				backupPath,
				err,
			),
		)
		return errors.Join(errs...)
	}

	// Backup selected directories
	for _, dir := range paths.BackupDirs() {
		_, fileName := filepath.Split(dir)
		destination := filepath.Join(backupPath, fileName)
		err = os.Rename(dir, destination)
		if err != nil {
			errs = append(errs, err)
		}
	}

	// Return if any backups failed
	if len(errs) > 0 {
		errs = append(
			errs,
			fmt.Errorf("failures occured during backup. Refusing to continue with data removal"),
		)
		return errors.Join(errs...)
	}
	logger.Infof("MicroOVN data backed up to %s", backupPath)

	// Remove rest of the directories
	for _, dir := range paths.RequiredDirs() {
		err = os.RemoveAll(dir)
		if err != nil {
			errs = append(errs, fmt.Errorf("failed to remove directory '%s': %w", dir, err))
		}
	}

	return errors.Join(errs...)
}
