#!/bin/sh
# Load the environment
. "${SNAP_COMMON}/data/ovn.env"
export OVN_RUNDIR="${SNAP_COMMON}/run/switch/"
export OVN_NB_DB="${OVN_NB_CONNECT}"
export OVN_SB_DB="${OVN_SB_CONNECT}"

exec "$(basename ${0})" "${@}"
