#!/bin/sh
# Load the environment
. ${SNAP}/commands/ovn-sb

# importing OVS_RUNDIR, since ovn-trace may also interrogate the local Open vSwitch instance
. "${SNAP}/ovn.env"

exec ovn-trace -c "$CERT" -p "$KEY" -C "$CA_CERT" "${@}"
