#!/bin/sh
. "${SNAP}/ovn.env"

# Optionally load SSL certificates if they are readable
if [ -r "$OVN_PKI_DIR" ]; then
    CERT="${OVN_PKI_DIR}/client-cert.pem"
    KEY="${OVN_PKI_DIR}/client-privkey.pem"

    exec  "$(basename ${0})" -c "$CERT" -p "$KEY" -C "$CA_CERT" "${@}"
else
    exec "$(basename ${0})" "${@}"
fi
