name: Automatic documentation checks

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spellcheck:
    name: Spelling check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Aspell
        run: |
          sudo apt-get install aspell aspell-en

      - name: Install the doc framework
        run: |
          make install

      - name: Build docs and run spelling checker
        run: |
          make spelling

  woke:
    name: Inclusive language check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true
          woke-args: "*.rst **/*.rst -c https://github.com/canonical-web-and-design/Inclusive-naming/raw/main/config.yml"

  linkcheck:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install the doc framework
        run: |
          make install

      - name: Run linkchecker
        run: |
          make linkcheck
