name: microovn
icon: microovn.png
base: core24
assumes:
 - snapd2.59
adopt-info: microovn
grade: devel
source-code: https://github.com/canonical/microovn.git
summary: Simple clustered OVN deployment
description: |-
 Self-contained self-deployment with clustering.

confinement: strict

slots:
  ovn-certificates:
    interface: content
    source:
      read:
        - "$SNAP_COMMON/data/pki"
  ovn-env:
    interface: content
    source:
      read:
        - "$SNAP_COMMON/data/env"
  ovn-chassis:
    interface: content
    source:
      write:
        - "$SNAP_COMMON/run/switch"

hooks:
  install:
    plugs:
      - network
      - network-control

apps:
  # Service
  daemon:
    command: commands/daemon.start
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
    slots:
      - microovn

  ovn-ovsdb-server-nb:
    command: commands/ovn-ovsdb-server-nb.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind

  ovn-ovsdb-server-sb:
    command: commands/ovn-ovsdb-server-sb.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind

  ovn-northd:
    command: commands/ovn-northd.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind

  frr-bgp:
    command: commands/frr-bgp.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
      - network-control

  frr-zebra:
    command: commands/frr-zebra.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
      - network-control

  chassis:
    command: commands/chassis.start
    daemon: simple
    install-mode: disable
    stop-command: commands/chassis.stop
    plugs:
      - network
      - network-bind
      - network-control
      - process-control
      - system-trace
      - hardware-observe

  switch:
    command: commands/switch.start
    daemon: simple
    install-mode: disable
    stop-command: commands/switch.stop
    plugs:
      - firewall-control
      - hardware-observe
      - hugepages-control
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace

  # Commands
  microovn:
    command: commands/microovn
    plugs:
      - network

  ovn-appctl:
    command: commands/ovn-appctl
    plugs:
      - network
  ovn-nbctl:
    command: commands/ovn-nbctl
    plugs:
      - network
      - network-bind
  ovn-sbctl:
    command: commands/ovn-sbctl
    plugs:
      - network
      - network-bind
  ovn-trace:
    command: commands/ovn-trace
    plugs:
      - network

  ovs-appctl:
    command: commands/ovs-appctl
    plugs:
      - network
  ovs-dpctl:
    command: commands/ovs-dpctl
    plugs:
      - network
      - network-control
  ovs-ofctl:
    command: commands/ovs-ofctl
    plugs:
      - network
  ovs-vsctl:
    command: commands/ovs-vsctl
    plugs:
      - network
  ovsdb-tool:
    command: bin/ovsdb-tool
  ovsdb-client:
    command: commands/ovsdb-client
    plugs:
      - network

  vtysh:
    command: commands/vtysh
    plugs:
      - network
      - network-bind
      - network-control

  refresh-expiring-certs:
    command: commands/refresh-expiring-certs
    daemon: oneshot
    timer: 02:00~02:30


parts:
  # Dependencies
  dqlite:
    source: https://github.com/canonical/dqlite
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
      - --enable-build-raft
    stage-packages:
      - libuv1
      - libsqlite3-0
      - liblz4-1
    build-packages:
      - make
      - libuv1-dev
      - liblz4-dev
      - libsqlite3-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libdqlite*so*
      - lib/libraft*so*
      - lib/*/libuv*so*
  rtrlib:
    build-packages:
      - cmake
      - make
      - gcc
      - libssh-dev
    stage-packages:
      - libssh-4
      - zlib1g
    prime:
      - usr/local/lib/librtr.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libssh.so*
    source: https://github.com/rtrlib/rtrlib.git
    source-type: git
    source-tag: v0.8.0
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
  libyang:
    build-packages:
      - cmake
      - make
      - gcc
      - libpcre2-dev
    stage-packages:
      - libpcre2-8-0
    source: https://github.com/CESNET/libyang.git
    source-type: git
    source-tag: v2.1.128
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DENABLE_LYD_PRIV=ON
      - -DENABLE_CACHE=ON
      - -DCMAKE_BUILD_TYPE:String="Release"
  frr:
    after: [rtrlib,libyang]
    build-packages:
      - gcc
      - autoconf
      - automake
      - libtool
      - make
      - gawk
      - libreadline-dev
      - libelf-dev
      - texinfo
      - libncurses5-dev
      - texlive-latex-base
      - texlive-latex-recommended
      - libcap-dev
      - imagemagick
      - ghostscript
      - groff
      - libpcre3-dev
      - chrpath
      - pkg-config
      - libjson-c-dev
      - libc-ares-dev
      - bison
      - flex
      - python3-dev
      - libprotobuf-c-dev
      - protobuf-c-compiler
      - python3-sphinx
    stage-packages:
      - coreutils
      - iproute2
      - logrotate
      - libjson-c5
      - libc-ares2
      - libatm1
      - libprotobuf-c1
      - libdb5.3
      - libacl1
      - libattr1
      - libaudit1
      - libselinux1
      - libxtables12
    plugin: autotools
    source: https://github.com/FRRouting/frr.git
    source-type: git
    source-tag: frr-10.1.1
    autotools-configure-parameters:
      - --disable-doc
      - --disable-ripd
      - --disable-ripngd
      - --disable-ospfd
      - --disable-ospf6d
      - --disable-ldpd
      - --disable-nhrpd
      - --disable-eigrpd
      - --disable-babeld
      - --disable-pimd
      - --disable-pim6d
      - --disable-vrrpd
      - --disable-pbrd
      - --disable-sharpd
      - --disable-isisd
      - --disable-ospfclient
      - --disable-ospfapi
      - --enable-vtysh
      - --enable-watchfrr
      - --enable-multipath=64
      - --enable-rtadv
      - --enable-user=root
      - --enable-group=root
      - --enable-fpm
      - --enable-protobuf
      - --enable-rpki
      - --enable-configfile-mask=0640
      - --enable-logfile-mask=0640
      - --sysconfdir=/etc
      - --localstatedir=/var
      - --sbindir=/sbin
      - --bindir=/bin
      - --prefix=/usr
    override-prime: |
      craftctl default
      # Pull in default config files for FRR to the expected location
      mkdir -p $CRAFT_PRIME/etc/frr
      cp $CRAFT_PART_SRC/tools/etc/frr/frr.conf $CRAFT_PRIME/etc/frr/
      cp $CRAFT_PART_SRC/tools/etc/frr/vtysh.conf $CRAFT_PRIME/etc/frr/

  ovn:
    plugin: autotools
    source: https://github.com/ovn-org/ovn.git
    source-type: git
    source-branch: branch-25.03
    override-build: |
      # build OVS first
      cd ovs
      ./boot.sh
      ./configure \
        --enable-ssl \
        --localstatedir=/var \
        --sysconfdir=/etc \
        --prefix=/usr
      make -j$CRAFT_PARALLEL_BUILD_COUNT
      # build OVN
      cd ..
      ./boot.sh
      ./configure \
        --prefix=/usr \
        --localstatedir=/var \
        --sysconfdir=/etc \
        --with-dbdir=/var/lib/ovn \
        --enable-ssl
      make -j$CRAFT_PARALLEL_BUILD_COUNT
      make install DESTDIR=$CRAFT_PART_INSTALL
      mkdir -p $CRAFT_PART_INSTALL/etc/ovn
    build-packages:
      - gcc
      - libssl-dev
      - libunbound-dev
      - python3
      - make
      - automake
      - autoconf
      - libtool-bin
      - pkgconf
    stage-packages:
      - libunbound8
    organize:
      usr/bin/: bin/
      usr/share/: share/
      usr/sbin/: bin/
      usr/lib/: lib/
    prime:
     - bin/ovn-appctl
     - bin/ovn-controller
     - bin/ovn-nbctl
     - bin/ovn-northd
     - bin/ovn-sbctl
     - bin/ovn-trace
     - etc/ovn
     - share/ovn
  ovs:
    plugin: nil
    stage-packages:
      - openvswitch-switch
    organize:
      usr/bin/: bin/
      usr/sbin/: bin/
      usr/lib/: lib/
      usr/share/: share/
    prime:
     - bin/ovs-appctl
     - bin/ovs-dpctl
     - bin/ovs-ofctl
     - bin/ovs-vsctl
     - bin/ovs-vswitchd
     - bin/ovsdb-client
     - bin/ovsdb-server
     - bin/ovsdb-tool
       # The lib cherry-picking is unfortunately necessary to avoid pulling in
       # external symlinks provided by the openssl package dependency.
       # (External symlinks, i.e. pointing at something in /, are not allowed.)
     - lib/*/libevent-2.1.so*
     - lib/*/libnuma.so.*
     - lib/*/bpf/*
     - lib/*/libbpf.so.*
     - lib/*/libxdp.so.*
     - lib/*/libunbound.so*
     - share/openvswitch
    override-build: |
        craftctl default

        mkdir -p "${CRAFT_PART_INSTALL}/bin/"
        mv "${CRAFT_PART_INSTALL}/usr/lib/openvswitch-switch/ovs-vswitchd" "${CRAFT_PART_INSTALL}/bin/"

  # Main part
  microovn:
    source: microovn/
    after:
      - dqlite
      - ovn
      - ovs
    build-snaps:
      - go/1.22/stable
      - golangci-lint
    plugin: nil
    override-pull: |
      craftctl default
      set -ex

      # Download the dependencies
      go get -d -v ./...
    override-build: |
      set -ex

      # Setup build environment
      export CGO_CFLAGS="-I${CRAFT_STAGE}/include/ -I${CRAFT_STAGE}/usr/local/include/"
      export CGO_LDFLAGS="-L${CRAFT_STAGE}/lib/ -L${CRAFT_STAGE}/usr/local/lib/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

      # Check that `golangci-lint` is happy with the code.
      golangci-lint run --verbose

      # Run any unit tests.
      LD_LIBRARY_PATH=${CRAFT_STAGE}/lib/:${CRAFT_STAGE}/usr/local/lib/ \
          go test ./...

      # Determine versions of packages used to build MicroOVN
      # Note (mkalcok): This code reaches into other snapcraft parts via hardcoded paths
      #                 to determine version of packages from which they were built. It
      #                 will require updates if these part names ever change.
      ovn_pkg_version=$(grep -E '^PACKAGE_VERSION' $CRAFT_PART_SRC/../../ovn/build/Makefile | \
                        awk '{print $NF;}')
      ovs_pkg_version=$(
          dpkg-deb -f \
          $CRAFT_PART_SRC/../../ovs/stage_packages/openvswitch-switch*.deb Version)
      git_version=$(
          git -C $CRAFT_PROJECT_DIR describe \
              --always \
              --dirty \
              --abbrev=10)
      
      craftctl set version=${ovn_pkg_version}+snap${git_version}
      
      version_package=github.com/canonical/microovn/microovn/version
      go_ldflags="-X '${version_package}.MicroOvnVersion=${git_version}' \
                  -X '${version_package}.OvnVersion=${ovn_pkg_version}' \
                  -X '${version_package}.OvsVersion=${ovs_pkg_version}'"
      # Build the binaries
      go build -o "${CRAFT_PART_INSTALL}/bin/microovn" \
               -ldflags "$go_ldflags" \
               ./cmd/microovn
      go build -o "${CRAFT_PART_INSTALL}/bin/microovnd" \
               -ldflags "$go_ldflags" \
               -tags=libsqlite3 \
               ./cmd/microovnd
    prime:
      - bin/microovn
      - bin/microovnd

  docs:
    plugin: nil
    source: docs/
    build-packages:
      - libpython3-dev
      - libxml2-dev
      - libxslt1-dev
      - make
      - python3-venv
      - rustc
      - cargo
    override-build: |
      set -ex
      make .sphinx/venv || ( cat .sphinx/venv/pip_install.log && exit 1 )
      make text
      rm -rf ${CRAFT_PART_INSTALL}/docs/microovn
      mkdir -p ${CRAFT_PART_INSTALL}/docs
      cp -pR _build/text ${CRAFT_PART_INSTALL}/docs/microovn
    stage:
      # drop doc starter pack boiler plate files
      - -docs/microovn/help-woke.*
      - -docs/microovn/readme.txt
      - -docs/microovn/setup.txt
      - -docs/microovn/_*

  wrappers:
    plugin: dump
    source: snapcraft/
    stage-packages:
      - jq
    organize:
      usr/bin/: bin/
      usr/lib/: lib/
    prime:
      - commands/*
      - ./*.env
      - bin/jq
      - lib/*/libjq.so*
      - lib/*/libonig.so*

layout:
  /var/tmp/frr:
    symlink: $SNAP_COMMON/data/frr/tmp
  /etc/frr:
    symlink: $SNAP_COMMON/data/frr/etc
