name: microovn
icon: microovn.png
base: core22
assumes:
 - snapd2.59
adopt-info: ovn
grade: stable
source-code: https://github.com/canonical/microovn.git
summary: Simple clustered OVN deployment
description: |-
 Self-contained self-deployment with clustering.

confinement: strict

hooks:
  install:
    plugs:
      - network
      - network-control

apps:
  # Service
  daemon:
    command: commands/daemon.start
    daemon: simple
    plugs:
      - network
      - network-bind
    slots:
      - microovn

  central:
    command: commands/central.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind

  chassis:
    command: commands/chassis.start
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
      - network-control
      - process-control
      - system-trace
      - hardware-observe

  switch:
    command: commands/switch.start
    daemon: simple
    install-mode: disable
    refresh-mode: endure
    plugs:
      - firewall-control
      - hardware-observe
      - hugepages-control
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace

  # Commands
  microovn:
    command: commands/microovn
    plugs:
      - network

  ovn-appctl:
    command: commands/ovn-appctl
    plugs:
      - network
  ovn-nbctl:
    command: commands/ovn-nbctl
    plugs:
      - network
  ovn-sbctl:
    command: commands/ovn-sbctl
    plugs:
      - network
  ovn-trace:
    command: commands/ovn-trace
    plugs:
      - network

  ovs-appctl:
    command: commands/ovs-appctl
    plugs:
      - network
  ovs-dpctl:
    command: commands/ovs-dpctl
    plugs:
      - network
      - network-control
  ovs-ofctl:
    command: commands/ovs-ofctl
    plugs:
      - network
  ovs-vsctl:
    command: commands/ovs-vsctl
    plugs:
      - network
  ovsdb-tool:
    command: bin/ovsdb-tool
  ovsdb-client:
    command: bin/ovsdb-client
    plugs:
      - network

  refresh-expiring-certs:
    command: commands/refresh-expiring-certs
    daemon: oneshot
    timer: 02:00~02:30


parts:
  # Dependencies
  dqlite:
    after:
      - raft
    source: https://github.com/canonical/dqlite
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - libsqlite3-0
    build-packages:
      - libuv1-dev
      - libsqlite3-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libdqlite*so*
      - lib/*/libuv*

  raft:
    source: https://github.com/canonical/raft
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - liblz4-1
    build-packages:
      - libuv1-dev
      - liblz4-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libraft*so*
      - lib/*/libuv.so*

  ovn:
    plugin: nil
    stage-packages:
      - ovn-central
      - ovn-host
    organize:
      usr/bin/: bin/
      usr/share/: share/
    prime:
     - bin/ovn-appctl
     - bin/ovn-controller
     - bin/ovn-nbctl
     - bin/ovn-northd
     - bin/ovn-sbctl
     - bin/ovn-trace
     - etc/ovn
     - share/ovn
    override-build: |
        craftctl default

        mkdir -p "${CRAFT_PART_INSTALL}/etc/ovn/"
    override-stage: |
        craftctl default
        pkg_version=$(
            dpkg-deb -f \
            $CRAFT_PART_SRC/../stage_packages/ovn-host*.deb \
            Version | sed -rne 's/([0-9.]+)[-+].*$$/\1/p')
        git_version=$(
            git -C $CRAFT_PROJECT_DIR describe \
                --always \
                --dirty \
                --abbrev=10)
        craftctl set version=${pkg_version}+snap${git_version}

  ovs:
    plugin: nil
    stage-packages:
      - openvswitch-switch
    organize:
      usr/bin/: bin/
      usr/sbin/: bin/
      usr/lib/: lib/
      usr/share/: share/
    prime:
     - bin/ovs-appctl
     - bin/ovs-dpctl
     - bin/ovs-ofctl
     - bin/ovs-vsctl
     - bin/ovs-vswitchd
     - bin/ovsdb-client
     - bin/ovsdb-server
     - bin/ovsdb-tool
     - lib/*
     - share/openvswitch
    override-build: |
        craftctl default

        mkdir -p "${CRAFT_PART_INSTALL}/bin/"
        mv "${CRAFT_PART_INSTALL}/usr/lib/openvswitch-switch/ovs-vswitchd" "${CRAFT_PART_INSTALL}/bin/"

  # Main part
  microovn:
    source: microovn/
    after:
      - dqlite
    build-snaps:
      - go
    plugin: nil
    override-pull: |
      craftctl default
      set -ex

      # Download the dependencies
      go get -d -v ./...
    override-build: |
      set -ex

      # Setup build environment
      export CGO_CFLAGS="-I${CRAFT_STAGE}/include/ -I${CRAFT_STAGE}/usr/local/include/"
      export CGO_LDFLAGS="-L${CRAFT_STAGE}/lib/ -L${CRAFT_STAGE}/usr/local/lib/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

      # Build the binaries
      go build -o "${CRAFT_PART_INSTALL}/bin/microovn" ./cmd/microovn
      go build -o "${CRAFT_PART_INSTALL}/bin/microovnd" -tags=libsqlite3 ./cmd/microovnd
    prime:
      - bin/microovn
      - bin/microovnd

  wrappers:
    plugin: dump
    source: snapcraft/
    stage-packages:
      - jq
