version: "2"
run:
  # The defualt timeout is now disabled but a timeout for 5m is good for the CI
  timeout: 5m
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        # disabling this check for now as the fact that it is excluded by default and other people are excluding it means its not needed.
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
