#!/bin/sh

# The ovs-dpctl tool calls directly into OVS dpif library functions, which for
# the system datapath means making calls to the kernel over a netlink socket.
#
# If there is an already running ovs-vswitchd process that has initialized this
# data path, it will be listed.
ovs-dpctl dump-dps 2>&1 | grep ovs-system > /dev/null
rc=$?
if [ $rc -eq 0 ]; then
        cat << EOF >&2
An already running copy of Open vSwitch detected in current namespace.

The microovn snap provides Open vSwitch.

Running multiple instances of Open vSwitch in the same namespace is not
supported.
EOF
	exit 1
fi

# Create directories required by FRR
frr_etc="$SNAP_COMMON/data/frr/etc/"
mkdir -p $frr_etc
mkdir -p "$SNAP_COMMON/data/frr/tmp"
mkdir -p "$SNAP_COMMON/run/frr"

# Seed default config files for FRR
cp -r --update=none "$SNAP"/etc/frr/* "$frr_etc"
