#!/bin/sh

# The ovs-dpctl tool calls directly into OVS dpif library functions, which for
# the system datapath means making calls to the kernel over a netlink socket.
#
# If there is an already running ovs-vswitchd process that has initialized this
# data path, it will be listed.
ovs-dpctl dump-dps 2>&1 | grep ovs-system > /dev/null
rc=$?
if [ $rc -eq 0 ]; then
        cat << EOF >&2
An already running copy of Open vSwitch detected in current namespace.

The microovn snap provides Open vSwitch.

Running multiple instances of Open vSwitch in the same namespace is not
supported.
EOF
	exit 1
fi

umask 077
# Create directories required by Bird
bird_data_dir="$SNAP_COMMON/data/bird"
mkdir -p "$bird_data_dir"
mkdir -p "$SNAP_COMMON/run/bird"

# Seed default config files for Bird routing daemon
cp -r --update=none "$SNAP/etc/bird/bird.conf" "$bird_data_dir"
